# db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZHBnLWNxc3ZxYjU2bDQ3YzczYTg3dGEwLWEub3JlZ29uLXBvc3RncmVzLnJlbmRlci5jb206NTQzMi9lZHVrYW5fNmJrYQ==
  DB_USERNAME: ZWR1a2FuXzZia2FfdXNlcg==
  DB_PASSWORD: cjZJclN1ODRBZFdhdjV5UVJvMk0xSklQSmo5b0duSFI=
